module.exports = {
  Text: require('./text'),
  Header: require('./header'),
  SubHeader: require('./sub-header'),
  SubSubHeader: require('./sub-sub-header'),
  List: require('./list'),
  ToDo: require('./to-do'),
  Code: require('./code'),
  Equation: require('./equation'),
  Quote: require('./quote'),
  Divider: require('./divider'),
  Image: require('./image'),
  Unknown: require('./unknown-block'),
  YouTubeVideo: require('./youtube-video'),
};
